const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');

const jsFiles = [
  '01-error-console.js',
  '02-config-data.js',
  '03-state-services.js',
  '04-auth.js',
  '05-router.js',
  'shared/html-utils.js',
  'pages/home.js',
  'pages/record.js',
  'pages/guide.js',
  'pages/game.js',
  'pages/leaderboard.js',
  'pages/community.js',
  'pages/chat.js',
  'pages/profile.js',
  'pages/impact-dashboard.js',
  'pages/admin.js',
  '99-runtime.js',
];

function readSource(file) {
  const sourcePath = path.join(root, 'src', 'js', file);
  if (!fs.existsSync(sourcePath)) {
    throw new Error(`Missing source file: ${path.relative(root, sourcePath)}`);
  }
  return fs.readFileSync(sourcePath, 'utf8').replace(/\s+$/u, '');
}

function buildJsBundle() {
  const outDir = path.join(root, 'assets', 'js');
  fs.mkdirSync(outDir, { recursive: true });

  const banner = [
    '// Generated by tools/build-assets.js.',
    '// Edit files in src/js, then run: node tools/build-assets.js',
    '',
  ].join('\n');

  const bundle = banner + jsFiles.map((file) => {
    const normalized = file.replace(/\\/g, '/');
    return `\n// ---- src/js/${normalized} ----\n${readSource(file)}\n`;
  }).join('\n');

  fs.writeFileSync(path.join(outDir, 'app.bundle.js'), bundle, 'utf8');
}

buildJsBundle();
console.log('Built assets/js/app.bundle.js');
